[  
{  
    "title":"标题1", 
    "src":"/images/art1.jpg",
    "context":"内容1内容1内容1内容1内容1内容1"  
},  
{  
    "title":"标题2",
    "src":"/images/art2.jpg",
    "context":"内容2内容2内容2内容2内容2内容2"  
},  
{  
    "title":"标题3",
    "src":"/images/art3.jpg",
    "context":"内容3内容3内容3内容3内容3内容3"  
}  
]  